### ISSUE TITLE
HAVE_REG_STARTEND is defined when REG_STARTEND is not

### ISSUE THREAD

**Issue by randyprice** [open5gs/freeDiameter#4]
from `extensions/rt_default/meson.build`, `HAVE_REG_STARTEND` is defined according to this block:

```
if cc.has_function('regexec', prefix : '#include <regex.h>')
  conf_data = configuration_data()
  conf_data.set('HAVE_REG_STARTEND', 1)
endif
```

However, this block is insufficient to determine whether `REG_STARTEND` is defined, as not all `regex.h` contain the macro. Something like the following in `extensions/rt_ereg/CMakeLists.txt` should be used instead:

```
CHECK_C_SOURCE_COMPILES("${CHECK_REG_STARTEND_SOURCE_CODE}" HAVE_REG_STARTEND)
IF (HAVE_REG_STARTEND)
     ADD_DEFINITIONS(-DHAVE_REG_STARTEND)
ENDIF (HAVE_REG_STARTEND)
```

**Comment by acetcom** [comment]
@randyprice 

I've resolve this issue and applied it to the r1.5.0 branch.

Please let me know if you have any other questions.

Thanks a lot!
Sukchan
